---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: pingworks/docker-ws-baseimg:0.2
      provision_command: mkdir -p /opt/chef/embedded/etc && echo "---\n:sources:\n- http://rubygems.org/" > /opt/chef/embedded/etc/gemrc

suites:
  - name: default
    run_list:
      - recipe[pw_base::default]
      - recipe[pw_base::gemrc]
      - recipe[pw_meetup::default]
    attributes:
